"""add tabla SolicitudCompra

Revision ID: 935708f9ac39
Revises: eeee8ab99754
Create Date: 2026-08-07 20:14:13.992174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935708f9ac39'
down_revision: Union[str, Sequence[str], None] = 'eeee8ab99754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_compra',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('id_usuario_creador', sa.BigInteger(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_usuario_modificador', sa.BigInteger(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_compra_estado'), 'solicitudes_compra', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_compra_solicitante_id'), 'solicitudes_compra', ['solicitante_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_compra_solicitante_id'), table_name='solicitudes_compra')
    op.drop_index(op.f('ix_solicitudes_compra_estado'), table_name='solicitudes_compra')
    op.drop_table('solicitudes_compra')
    # ### end Alembic commands ###
